spring.application.name=loging_spring_secqurity

spring.datasource.url = jdbc:mysql://localhost:3306/login_spring_secqurity
spring.datasource.username = root
spring.datasource.password = avijit@2005

spring.jpa.hibernate.ddl-auto=update
